=== DOCGroup/XSC/Examples/Library/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.w3.org/2001/XMLSchema XMLSchema.xsd"
            xmlns:lib="http://www.example.com/Lib"
            targetNamespace="http://www.example.com/Lib">

  <xsd:simpleType name="ISBN">
    <xsd:restriction base="xsd:unsignedLong"/>
  </xsd:simpleType>


  <xsd:complexType name="Title">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string"> 
        <xsd:attribute name="lang" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>


  <xsd:complexType name="Author">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="born" type="xsd:string"/>
      <xsd:element name="dead" type="xsd:string"/>
    </xsd:sequence>
    <xsd:attribute name="recommends" type="xsd:IDREF"/> <!-- Book -->
  </xsd:complexType>


  <xsd:complexType name="Character">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="qualification" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="Genre">
    <xsd:restriction base="xsd:NCName">
      <xsd:enumeration value="romance"/>
      <xsd:enumeration value="fiction"/>
      <xsd:enumeration value="horror"/>
      <xsd:enumeration value="history"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="Book">
    <xsd:sequence>
      <xsd:element name="isbn" type="lib:ISBN"/>
      <xsd:element name="title" type="lib:Title"/>
      <xsd:element name="genre" type="lib:Genre"/>
      <xsd:element name="author" type="lib:Author" maxOccurs="unbounded"/>
      <xsd:element name="character" type="lib:Character" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="available" type="xsd:boolean" use="required"/>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
  </xsd:complexType>


  <xsd:complexType name="Library">
    <xsd:sequence>
      <xsd:element name="book" type="lib:Book" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>


  <xsd:element name="library" type="lib:Library"/>

</xsd:schema>

=== DOCGroup/XSC/Examples/Library/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:library xmlns:l="http://www.example.com/Lib"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:schemaLocation="http://www.example.com/Lib library.xsd">

  <book id="WP" available="true" >
    <isbn>0140444173</isbn>
    <title>War and Peace</title>
    <genre>history</genre>

    <author recommends="MM">
      <name>Lev Tolstoy</name>
      <born>1922-11-26</born>
      <dead>2000-02-12</dead>
    </author>

    <character>
      <name>Natasha Rostova</name>
      <qualification>a woman of convivial and amorous habits</qualification>
    </character>
    <character>
      <name>Pierre Bezukhov</name>
      <qualification>a man of convivial and amorous habits</qualification>
    </character>
    <character>
      <name>Napoleon</name>
      <qualification>french guy</qualification>
    </character>
  </book>

  <book id="MM" available="false">
    <isbn>0802130119</isbn>
    <title>The Master and Margarita</title>
    <genre>fiction</genre>

    <author recommends="WP">
      <name>Mikhail Bulgakov</name>
      <born>1922-11-26</born>
      <dead>2000-02-12</dead>
    </author>

    <character>
      <name>Master</name>
      <qualification></qualification>
    </character>
    <character>
      <name>Margarita</name>
      <qualification></qualification>
    </character>
    <character>
      <name>Behemot</name>
      <qualification>funky cat</qualification>
    </character>
    <character>
      <name>Voland</name>
      <qualification></qualification>
    </character>
  </book>

</l:library>
